import { Box, Button, Container, Heading, Image, List, Link, ListItem, Icon, useColorModeValue, SimpleGrid } from '@chakra-ui/react'
import NextLink from 'next/link'
import Head from 'next/head'
import Paragraph from '../components/Paragraph'
import Section from '../components/section'
import { ChevronRightIcon } from '@chakra-ui/icons'
import { BioSection, BioYear } from '../components/Bio'
import { GridItem } from '@chakra-ui/react'
import Layout from '../components/layouts/article'
import { IoLogoTwitter, IoLogoInstagram, IoLogoGithub } from 'react-icons/io5'
import thumbYouTube from '../public/images/links/youtube.png'
import thumbInkdrop from '../public/images/miki.jpg'


export default function Page() {
  return (
    <Layout>
      <Container maxW="container.md">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Box borderRadius="lg" bg={useColorModeValue('whiteAlpha.500', 'whiteAlpha.200')} p={3} align="center" mb={6}>
          Hello, I am a full stack developer based in Ethiopia, Addis Ababa
        </Box>

        <Box display={{ md: "flex" }}>
          <Box flexGrow={1}>
            <Heading as="h2" variant="page-title">
              Milkias Hailu
            </Heading>
            <p>Digital Craftzman ( Developer / Designer / 3dArtist )</p>
          </Box>
          <Box
            flexShrink={0}
            mt={{ base: 4, md: 0 }}
            ml={{ md: 6 }}
            textAlign="center"
          >
            <Image
              rounded="md"
              borderColor={useColorModeValue('whiteAlpha.800', 'whiteAlpha.200')}
              borderWidth={4}
              borderRadius='full'
              boxSize='200px'
              borderStyle="solid"
              width={240}
              height={140}
              src="/images/miki.jpg"
              objectFit='cover'
              alt="Profile image"
            />
          </Box>
        </Box>

        <Section delay={0.1}>
          <Heading as="h3" variant="section-title">
            Work
          </Heading>
          <Paragraph>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Tellus pellentesque eu tincidunt tortor aliquam nulla.
            Interdum velit laoreet id donec ultrices tincidunt arcu. Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Tristique sollicitudin nibh sit amet. Vitae purus faucibus ornare suspendisse.
            Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Sed velit dignissim sodales ut eu sem integer vitae. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Vivamus at augue eget arcu. Netus et malesuada fames ac turpis egestas integer eget aliquet.
            Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. In arcu cursus euismod quis viverra. Eu non diam phasellus vestibulum called{' '}<NextLink href="/works/inkdrop"><Link>InkDrop</Link></NextLink>
          </Paragraph>
          <Box align="center" my={4}>
            <NextLink href="/works">
              <Button rightIcon={<ChevronRightIcon />} colorScheme="teal">
                My portfolio
              </Button>
            </NextLink>
          </Box>
        </Section>

        <Section delay={0.2}>
          <Heading as="h3" variant="section-title">
            Bio
          </Heading>
          <BioSection>
            <BioYear>1998</BioYear>
            Born in Ethiopia, (ኢትዮጵያ) 🇪🇹 Addis Ababa.
          </BioSection>
          <BioSection>
            <BioYear>2017-2021</BioYear> Completed bachelors degree in computer Science in Addis Ababa University of computaional Science in the year of 2021 (2020-2021 no school due to covid-19)
          </BioSection>
          <BioSection>
            <BioYear>2020-2021</BioYear> Acquired intermidate skills in Blender 3d in areas including modeling, animating and rendering quality images.
            Got into learning react and next js in the summer and liked it well. Got into react native and started developing for android and ios
          </BioSection>
          <BioSection>
            <BioYear>2022-current</BioYear> Freelance work in Design and Developing Mobile and Web Applications, and on the side i do 3d Renders and animations as well
          </BioSection>
        </Section>

        <Section delay={0.3}>
          <Heading as="h3" variant="section-title">
            I ♥
          </Heading>
          <Paragraph>
            Art, Music,{' '}
            <Link href="https://illust.odoruinu.net/" target="_blank">
              Drawing
            </Link>
            , Playing Drums,{' '}
            <Link href="https://500px.com/p/craftzdog" target="_blank">
              Photography
            </Link>
            , Leica, Machine Learning
          </Paragraph>
        </Section>

        <Section delay={0.3}>
          <Heading as="h3" variant="section-title">
            On the web
          </Heading>
          <List>
            <ListItem>
              <Link href="https://github.com/milkiascha7" target="_blank">
                <Button
                  variant="ghost"
                  colorScheme="teal"
                  leftIcon={<Icon as={IoLogoGithub} />}
                >
                  @milkas_hailu
                </Button>
              </Link>
            </ListItem>
            <ListItem>
              <Link href="https://twitter.com/MilkiasHchach" target="_blank">
                <Button
                  variant="ghost"
                  colorScheme="teal"
                  leftIcon={<Icon as={IoLogoTwitter} />}
                >
                  @MilkiasHchach (English)
                </Button>
              </Link>
            </ListItem>

            <ListItem>
              <Link href="https://www.instagram.com/digital_program7/" target="_blank">
                <Button
                  variant="ghost"
                  colorScheme="teal"
                  leftIcon={<Icon as={IoLogoInstagram} />}
                >
                  @digital_program7
                </Button>
              </Link>
            </ListItem>
          </List>

          <SimpleGrid columns={[1, 2, 2]} gap={6}>
            <GridItem
              href="https://www.youtube.com/devaslife"
              title="Dev as Life"
              thumbnail={thumbYouTube}
            >
              My YouTube channel
            </GridItem>
            <GridItem
              href="https://www.inkdrop.app/"
              title="Inkdrop"
              thumbnail={thumbInkdrop}
            >
              A Markdown note-taking app
            </GridItem>
          </SimpleGrid>

          <Box align="center" my={4}>
            <NextLink href="/posts">
              <Button rightIcon={<ChevronRightIcon />} colorScheme="teal">
                Popular posts
              </Button>
            </NextLink>
          </Box>
        </Section>


      </Container>
    </Layout>
  )
}
export { getServerSideProps } from '../components/chakra'